version: '3.9'

services:
  gdlhub-app:
    container_name: gdlhub-app
    build:
      context: ./gdlhub-app
      args:
        - MODE=${MODE}
    env_file:
      - .env
    environment:
      - MODE=${MODE}
    volumes:
      - ./gdlhub-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install &&
             if [ \"$MODE\" = 'production' ]; then
               npm run build && npm run preview -- --host;
             else
               npm run dev;
             fi"


  gdlhub-api:
    container_name: gdlhub-api
    build:
      context: ./gdlhub-api
      args:
        - MODE=${MODE}
    environment:
      - MODE=${MODE}
      - APIPORT=${APIPORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./gdlhub-api:/app
      - ./db:/app/db  
      - /app/node_modules
    ports:
      - "${APIPORT}:${APIPORT}"
    depends_on:
      - gdlhub-postgres
    command: >
      sh -c "npm install &&
             if [ \"$MODE\" = 'production' ]; then
               npm start;
             else
               npm run dev;
             fi"

  gdlhub-postgres:
    container_name: gdlhub-postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./db/migration:/docker-entrypoint-initdb.d


volumes:
  postgres-data:
