services:
  gdlhub-app:
    container_name: gdlhub-app
    build:
      context: ./gdlhub-app
      args:
        - MODE=${MODE}
    env_file:
      - .env
    environment:
      - MODE=${MODE}
    volumes:
      - ./gdlhub-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install &&
             if [ \"$MODE\" = 'production' ]; then
               npm run build;
             else
               npm run dev;
             fi"


  gdlhub-api:
    container_name: gdlhub-api
    build:
      context: ./gdlhub-api
      args:
        - MODE=${MODE}
    environment:
      - MODE=${MODE}
    volumes:
      - ./gdlhub-api:/app
      - ./db:/app/db  
      - /app/node_modules
    env_file:
      - .env  
    ports:
      - "${APIPORT}:${APIPORT}"
    depends_on:
      - gdlhub-postgres
      - postfix
    command: >
      sh -c "npm install &&
             if [ \"$MODE\" = 'production' ]; then
               npm start;
             else
               npm run dev;
             fi"

  gdlhub-postgres:
    container_name: gdlhub-postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./db/migration:/docker-entrypoint-initdb.d

  # Postfix SMTP Server para envío real de emails
  postfix:
    container_name: gdlhub-postfix
    image: boky/postfix:latest
    restart: always
    ports:
      - "587:587"   # Puerto SMTP submission  
    environment:
      - HOSTNAME=${EMAIL_DOMAIN:-gdlhub.app}
      - ALLOWED_SENDER_DOMAINS=${EMAIL_DOMAIN:-gdlhub.app}
    volumes:
      - postfix-data:/var/spool/postfix


volumes:
  postgres-data:
  postfix-data:
