version: '3.9'

services:
  gdlhub.app:
    build:
      context: ./gdlhub.app
      args:
        - MODE=${MODE}
    environment:
      - MODE=${MODE}
    volumes:
      - ./gdlhub.app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "if [ \"$MODE\" = 'production' ]; then
               npm run build && npm run preview -- --host;
             else
               npm run dev;
             fi"

  gdlhub.api:
    build:
      context: ./gdlhub.api
      args:
        - MODE=${MODE}
    environment:
      - MODE=${MODE}
    volumes:
      - ./gdlhub.api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "if [ \"$MODE\" = 'production' ]; then
               npm start;
             else
               npm run dev;
             fi"
