version: '3.9'

services:
  gdlhub-app:
    build:
      context: ./gdlhub-app
      args:
        - MODE=${MODE}
    environment:
      - MODE=${MODE}
    volumes:
      - ./gdlhub-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "if [ \"$MODE\" = 'production' ]; then
               npm run build && npm run preview -- --host;
             else
               npm run dev;
             fi"

  gdlhub-api:
    build:
      context: ./gdlhub-api
      args:
        - MODE=${MODE}
    environment:
      - MODE=${MODE}
      - APIPORT=${APIPORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./gdlhub-api:/app
      - /app/node_modules
    ports:
      - "${APIPORT}:${APIPORT}"
    depends_on:
      - gdlhub-postgres
    command: >
      sh -c "if [ \"$MODE\" = 'production' ]; then
               npm start;
             else
               npm run dev;
             fi"

  gdlhub-postgres:
    image: postgres:16
    container_name: gdlhub-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
